name: advancio_test
description: A new flutter project
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dio_http_cache: ^0.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_screenutil: ^5.6.1
  flutter_svg: ^2.0.0+1
  gap: ^2.0.1
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  hexcolor: ^3.0.1
  pin_code_fields: ^7.4.0
  pretty_dio_logger: ^1.1.1
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.8
  sqflite: ^2.2.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
    - assets/svgs/
    - assets/gifs/
